// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using blazor_strategy_and_factory.Data;

#nullable disable

namespace blazor_strategy_and_factory.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    partial class FinancialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("blazor_strategy_and_factory.Models.Database.BudgetRecord", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUDGET_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<decimal>("ActualAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("ACTUAL_AMOUNT");

                    b.Property<int>("BudgetMonth")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUDGET_MONTH");

                    b.Property<int>("BudgetYear")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BUDGET_YEAR");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DEPARTMENT");

                    b.Property<decimal>("PlannedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("PLANNED_AMOUNT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGION");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<decimal>("Variance")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VARIANCE");

                    b.HasKey("BudgetId");

                    b.HasIndex("Department");

                    b.HasIndex("Region");

                    b.HasIndex("BudgetYear", "BudgetMonth");

                    b.ToTable("BUDGET_RECORDS");
                });

            modelBuilder.Entity("blazor_strategy_and_factory.Models.Database.CompanyAnnouncement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANNOUNCEMENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<DateTime>("AnnouncementDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ANNOUNCEMENT_DATE");

                    b.Property<string>("AnnouncementType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ANNOUNCEMENT_TYPE");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("NCLOB")
                        .HasColumnName("CONTENT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("ImportanceLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("IMPORTANCE_LEVEL");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGION");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("AnnouncementDate");

                    b.HasIndex("AnnouncementType");

                    b.HasIndex("Region");

                    b.ToTable("COMPANY_ANNOUNCEMENTS");
                });

            modelBuilder.Entity("blazor_strategy_and_factory.Models.Database.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("DEPARTMENT");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMPLOYEE_NAME");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("HIRE_DATE");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("POSITION");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGION");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("SALARY");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Department");

                    b.HasIndex("Region");

                    b.ToTable("EMPLOYEES");
                });

            modelBuilder.Entity("blazor_strategy_and_factory.Models.Database.FinancialRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RECORD_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RECORD_DATE");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGION");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TRANSACTION_TYPE");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("RecordId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RecordDate");

                    b.HasIndex("Region");

                    b.HasIndex("EmployeeId", "RecordDate");

                    b.ToTable("FINANCIAL_RECORDS");
                });

            modelBuilder.Entity("blazor_strategy_and_factory.Models.Database.MarketData", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DATA_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DataId"));

                    b.Property<decimal>("ChangePercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("DECIMAL(8,4)")
                        .HasColumnName("CHANGE_PERCENT");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("CLOSE_PRICE");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<decimal>("HighPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("HIGH_PRICE");

                    b.Property<decimal>("LowPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("LOW_PRICE");

                    b.Property<DateTime>("MarketDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("MARKET_DATE");

                    b.Property<string>("MarketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MARKET_TYPE");

                    b.Property<decimal>("OpenPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("OPEN_PRICE");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("REGION");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SYMBOL");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<long>("Volume")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VOLUME");

                    b.HasKey("DataId");

                    b.HasIndex("MarketDate");

                    b.HasIndex("Region");

                    b.HasIndex("Symbol");

                    b.HasIndex("Symbol", "MarketDate");

                    b.ToTable("MARKET_DATA");
                });
#pragma warning restore 612, 618
        }
    }
}
